services:
  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - PORT=3000
      - MONGODB_URI=${MONGODB_URI}
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    networks:
      - app-network

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo_data:
